accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'

urlpatterns = [
    url(r'^$', views.be_together, name='be_together'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^chat/',include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
]

website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('to_gather/', views.to_gather, name='to_gather'),
    path('to_gather/<int:pk>/', views.to_gather_list, name='to_gather_list'),
    path('to_gather/new/', views.to_gather_new, name='to_gather_new'),  # 새로운 글 쓰기 위함
    path('to_gather/<int:pk>/edit/', views.to_gather_edit, name='to_gather_edit'),  # 글 수정 위함
    path('come_together/', views.come_together, name='come_together'),

]

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from channels.db import database_sync_to_async


async def connect(self):
    self.username = await database_sync_to_async(self.get_name)()


def get_name(User):
    return User.objects.all()[0].name

website/models.py
from django.conf import settings
from django.db import models
from django.db.models import *
from django.utils import timezone
from django.views import View

# to_gather 모델
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now, null = True)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

website/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth


# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['username'], password=request.POST['password1'])
            auth.login(request, user)
            return render(request, 'login.html')
        return render(request, 'signup.html')

    return render(request, 'signup.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, 'login.html', {'error': 'username or password is not correct'})
    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return render(request, 'after_logout.html')

chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json


def be_together(request):
    return render(request, 'be_together.html', {})


def room(request, room_name):
    return render(request, 'room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })

website/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from django.views import View
from .forms import PostForm
from django.http import HttpResponseRedirect


# Create your views here.

# main view 관련
def main(request):
    return render(request, 'website/main.html', {})


# to_gather view 관련
def to_gather(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'website/to_gather.html', {'posts': posts})


def to_gather_list(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'website/to_gather_list.html', {'post': post})


def to_gather_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():  ## 잘못된 값이 저장되는 것을 방지하기 위해
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('to_gather_list', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'website/to_gather_edit.html', {'form': form})  # 새로운 글 만드는 view


def to_gather_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(instance=post)
        if form.is_valid():
            post = form.save(commit = False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('to_gather_list', pk=post.pk)

    else:
        form = PostForm(instance=post)
    return render(request, 'website/to_gather_edit.html', {'form': form})  # 글 수정하는 view


# come_together view 관련
def come_together(request):
    return render(request, 'website/come_together.html', {})

accounts/templates/after_logout.html
{% extends 'website/base.html' %}

{% block contents %}
<h1 style="margin-left: 7%">Good Bye!</h1>
<br>
<div class="container">
    <h2>다른 계정으로 로그인 하기</h2>
    <br>
    <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        USERNAME:
        <br>
        <input name="username" type="text">
        <br>
        PASSWORD:
        <br>
        <input name="password" type="password">
        <br><br>
        <input type="submit" class="button" value="LOG IN" style="margin-right: 47%">
    </form>
</div>
{% endblock %}

accounts/templates/login.html
{% extends 'website/base.html' %}

{% block contents %}

<div class="modal">
</div>
<div class="container">
    <h1>LOG IN</h1>

    <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        USERNAME:
        <br>
        <input name="username" type="text">
        <br>
        PASSWORD:
        <br>
        <input name="password" type="password">
        <br><br>
        <input type="submit" class="button" value="LOG IN" style="margin-right: 47%">
    </form>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends 'website/base.html' %}

{% block contents %}
<div class="container">
    <h1>SIGN UP!</h1>

    <form method="POST" action="{% url 'signup' %}">
        {% csrf_token %}
        USERNAME:
        <br>
        <input name="username" type="text">
        <br>
        PASSWORD:
        <br>
        <input name="password1" type="password">
        <br>
        CONFIRM PASSWORD:
        <br>
        <input name="password2" type="password">
        <br><br>
        <input type="submit" class="button" value="SIGN UP" style="margin-right: 47%;">
    </form>
</div>
{% endblock %}

chat/templates/be_together.html
{% extends 'website/base.html'%}

{% block contents %}
    <br>
    <h2><b>What chat room would you like to enter?</b></h2>
    <br><br>
    <input id="room-name-input" type="text" size="100">
    <input class="button" id="room-name-submit" type="button" value="Enter"
    style="margin-right: 10%; margin-left: -10%; margin-top: -0.5%">
    {%for chat in chats %}
        <li><a href="{% url 'be_together_list' pk=chat.pk %}">{{chat.title}}</a></li>
    {%endfor%}
<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };
    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>
{% endblock %}

chat/templates/index.html
{% extends 'website/base.html' %}

{% block category_content %}

{% endblock %}

{% block list_content %}
<p>What chat room would you like to enter?</p><br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>
{% endblock %}
<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };
    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>

chat/templates/room.html
{% extends 'website/base.html' %}
{% load static %}

{% block css %}
    <style rel="stylesheet" href="{% static "css/room.css" %}"></style>
{% endblock %}

{% block menu_be_together %}
{% endblock %}

{% block contents %}
    <h1>{{ room_name_json }} 채팅방</h1>
    <br>
    <textarea id="chat-log" cols="100" rows="20"></textarea>
    <br><br><br>
    <input id="chat-message-input" type="text" size="90" style="margin-left: 10%">
    <input class="button" id="chat-message-submit" type="button" value="Send"
           style="margin-right: 15%; margin-left: -5%; margin-top: -0.5%">


<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
{% endblock %}

website/templates/website/base.html
{% load static %}

<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/dropdown.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/aos@2.3.1/dist/aos.css" />

    {% block css %}
    {% endblock %}

    <title>TOGETHER</title>
</head>

<body>

<header>
  <div rel="main.html" class="div_logo">
    <img src="/static/img/together-logo.png" width="150" height="80" align="left">
  </div>

  <div class="div_header_bar">
  <ul id="main-menu">
    <li><a href="main.html">ABOUT TOGETHER</a></li>
    <li><a href="#">TO GATHER</a>
      <ul id="sub-menu">
        <li><a href="#" aria-label="subemnu">submenu</a></li>

      </ul>
    </li>
    <li><a href="#">BE TOGETHER</a>
      <ul id="sub-menu">
        <li><a href="#" aria-label="subemnu">submenu</a></li>

      </ul>
    </li>
    <li><a href="come_together.html">COME TOGETHER</a>
      <ul id="sub-menu">

      </ul>
    </li>
      <button class="button button2">SIGN UP</button>
      <button class="button button1" >SIGN IN</button>


        </div>
  </header>

      <div class="div_menu"> <!--menu에 대한 class입니다. 현재 페이지 뷰에 맞게 bold 처리만 해주세요. -->
        <a href="{% url 'main' %}" id="menu_button_together">

          <br style="font-size: 10px">
        </a>
        <a href="{% url 'to_gather' %}" id="menu_button_to_gather">
          <br style="font-size: 10px">
        </a>
        <a href="{% url 'chat:be_together' %}" id="menu_button_be_together">
          <br style="font-size: 10px"></a>
        </div>

    <div rel="main.html" class="div_logo">
        <img src="/static/img/together-logo.png" width="150" height="80" align="left">
    </div>
    <div class="div_header_bar">
        <ul id="main-menu">
            <li><a href="{% url 'main' %}">ABOUT TOGETHER</a></li>
            <li><a href="{% url 'to_gather' %}">TO GATHER</a>
                <ul id="sub-menu">
                    <li><a href="#" aria-label="subemnu">submenu</a></li>
                </ul>
            </li>
            <li><a href="{% url 'chat:be_together' %}">BE TOGETHER</a>
                <ul id="sub-menu">
                    <li><a href="#" aria-label="subemnu">submenu</a></li>
                </ul>
            </li>
            <li><a href="{% url 'come_together' %}">COME TOGETHER</a>
            </li>
            {% if user.is_active %}
                <a href="" class="button"> {{user.username}}</a>
                <a href="{% url 'logout' %}" class="button">LOG OUT</a>
            {% else %}
                <a href="{% url 'signup' %}" class="button">SIGN UP</a>
                <a href="{% url 'login' %}" class="button"> LOG IN</a>
            {% endif %}
    </div>

  <div class="div_menu"> <!--menu에 대한 class입니다. 현재 페이지 뷰에 맞게 bold 처리만 해주세요. -->
    <a href="main.html" id="menu_button_together">
        <br style="font-size: 10px">
    </a>
    <a href="{% url 'to_gather' %}" id="menu_button_to_gather">
        <br style="font-size: 10px">
    </a>
    <a href="{% url 'chat:be_together' %}" id="menu_button_be_together">
        <br style="font-size: 10px"></a>
</div>

  <div rel="" class="div_contents">
          {%block contents%}

          {%endblock%}

  </div>


      <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    </body>
</html>

website/templates/website/come_together.html
{% load static %}
 <!DOCTYPE html>
 <html>
 	<head>
 		<meta charset="utf-8">
 		<title>TOGETHER</title>
    <link rel="stylesheet" href="{% static 'css/come_together.css' %}" />
    <link rel="stylesheet" href="{% static 'css/come_together_hover.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
 	</head>

 	<body>
    <div class="container">
      <br><br><br><br>
      <pre>
      <h1 style="font-size: 7.5vmin; text-align=center;"> Come Together Better Together!</h1>
      <br>
      <h1> We've just started off :)  </h1>
      <hr style="border:dashed 1px grey; width:400px;">
    </pre>
      <br><br><br><br><br><br>
      <pre>
        <strong><p>우리는 이제 막 시작했을 뿐입니다. 순항중이지만 조금씩 흔들리는 건 어쩔 수 없는 일입니다.</p></strong><br>
        <strong><p>그렇기에 우리는 당신이 필요합니다. </p></strong><br>
      <p> 우리가 Together을 시작하게 된 계기는 여기에 있습니다 </p><br><br>
      <img id = "image" src="/static/img/come_together.png" width="1000" height="500">
      <div class="together">
      <b id="together" style="font-size: 9vmin;">T</b><b>&nbsp;&nbsp;ry our personal best</b><br>
      <b id="together" style="font-size: 9vmin;">O</b><b>&nbsp;&nbsp;rganize our things</b><br>
      <b id="together" style="font-size: 9vmin;">G</b><b>&nbsp;&nbsp;etting our works done</b><br>
      <b id="together" style="font-size: 9vmin;">E</b><b>&nbsp;&nbsp;xpressing our ideas</b><br>
      <b id="together" style="font-size: 9vmin;">T</b><b>&nbsp;&nbsp;hinking deeply</b><br>
      <b id="together" style="font-size: 9vmin;">H</b><b>&nbsp;&nbsp;elping others</b><br>
      <b id="together" style="font-size: 9vmin;">E</b><b>&nbsp;&nbsp;nriching our minds</b><br>
      <b id="together" style="font-size: 9vmin;">R</b><b>&nbsp;&nbsp;specting each other</b><br>


      <br>
      <p> 'Together' 을 통해서 우리는 다양한 것을 할 수 있습니다.</p><br>
      :<p><strong><u>&nbsp;도전, 조직, 표현, 사고, 협업, 공유, 공감 </u></strong></p><br>
      <p> 그리고 이것은 확장, 연결, 통합 이 세 가지의 과정으로 나타내질 수 있습니다</p>


  </div>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

  </div>
  <div class="container_2">
    <br><br><br><br><br>
    <figure class="snip1200">
    <img src="/static/img/connect.png" />
    <figcaption>
      <div class="heading">
        <p>연결</p>
      </div>
    </figcaption>
  </figure>
  <figure class="snip1200">
  <img src="/static/img/share.png" />
  <figcaption>
    <div class="heading">
    </div>
  </figcaption>
</figure>
<figure class="snip1200">
<img src="/static/img/integrate.png" />
<figcaption>
  <div class="heading">
  </div>
</figcaption>
</figure>
<div class="line1"></div>
<div class="line2"></div>
<div class="line3"></div>
<div id="with">

<a href="https://github.com/jnl1128/sharing-together-website.git"> <img src ="/static/img/with_together.png" width="300" height="300"></a><br><br><br><br><br><br><br><br><br>
<pre style="font-size:2.4vmin; text-align:center">
"우리는 어쩌면 이보다 더 완벽해질 수 있습니다
혹 지금과는 차원이 다른 모습이 될 수도 있죠
하지만 우리는 이 길이 더 나아지는 길이라는 것은
분명히 알고 있습니다
Together은 협업 플랫폼인만큼
협업을 중요시하게 생각합니다
우리와 함께 나은 미래를 그려가볼까요?
We can be better If we are TOGETHER
If you click the image,
you can move to
our Git repository address"
- Cho, Jung, and Kim </pre>
</div>




</div>


    <div class="screen">
      <div class="road">
      <img src="/static/img/road.png"  width="275" height="300" align="center">
    </div>
    <div class="bike-screen">
      <div class="bike">
        <div class="left-handle"></div>
        <div class="right-handle"></div>
        <div class="headlight"></div>
        <div class="left-suspension"></div>
        <div class="left-support"></div>
        <div class="right-suspension"></div>
        <div class="right-support"></div>
        <div class="body"></div>
        <div class="wheel"></div>
      </div>
    </div>

  </div>



		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>

    $(".screen").click(function() {
    	var el = $(this),
    			newone = el.clone(true);

    	el.before(newone);
    	$(el).remove();
    });
    </script>

    <script>
    $(".hover").mouseleave(
  function () {
    $(this).removeClass("hover");
      }
      );
    </script>

    </body>
</html>

website/templates/website/main.html
{% load static %}
 <!DOCTYPE html>
 <html>
 	<head>
 		<meta charset="utf-8">
 		<title>TOGETHER</title>
		<link rel="stylesheet" href="https://unpkg.com/aos@2.3.1/dist/aos.css" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/button.css' %}"/>

 	</head>
 	<body>
		<div class="backgrounds overlay">
            <div class="background" data-aos="fade-in" data-aos-duration="1500" data-aos-anchor=".section--hero"></div>
		</div>
		<section class="section section--code">
			<div class="container">
				<h2 class="section-title" data-aos= "fade-in" data-aosduration= "400">WHY TOGETHER?</h2>
				<br>
				<div class="section-header" data-aos="fade-up">
					<pre><code class="html" style= "color:white ; font-size: 6vmin;">TO GATHER? BE TOGETHER!</code></pre>
				</div>
				<img src="/static/img/together.png" width="300" height="450" align="right">
                <pre><code data-aos="fade-down" data-aos-easing="ease" data-aos-delay="800" style= "color:white ; font-size: 4vmin;">이제 우리는 더 똑똑해질 수 있습니다. </code></pre>
				<br>
				<br>
				<div class="section-contents" data-aos="fade-in" data-aos-easing="ease" data-aos-delay="1500" style= "color:white; font-size: 2vmin;">
				<pre><code>인터넷의 발전은 우리에게 동일한 시간의 흐름 속에 묶인 단일한 그리고 무한의 공간을 제공해주었습니다</code></pre>
				<pre><code>하나의 네트워크 속에 놓인 우리는 더 나아질 수 있는 방법을 이미 알고 있습니다 </code></pre>
				<br>
				<pre><code style= "font-size: 3vmin;">공유, 共有 Sharing</code></pre>
				<br>
				<pre><code>공유, 공유하는 것, 공유하는 것의 힘</code></pre>
				<br>
				<pre><code>Together의 시작은 바로 여기에 있습니다</code></pre>
				<pre><code>같은 네트워크 공간 안에서 같은 시간의 흐름을 공유하는 우리들은 이제 문제점과 해결 방법을 공유할 수 있습니다. </code></pre>
				<br>
				<br>
				<br>
                    <pre><code>Together을 통해 경험하세요, 공유의 힘을.</code></pre>
				<br>
				<br>
 			</div>
            </div>
        </section>
        <section class="section section--code">
            <div class="container">
                <h2 class="section-title" data-aos="fade-right" data-aos-delay="400">BETTER TOGETHER</h2>
                <img src="/static/img/community.png" width="200" height="200" align="right" data-aos="fade-in" data-aos-dely="400">
                <div class="secton-header" data-aos="fade-left" data-aos-delay="800" style="color:white;">
                    <br>
                    <pre style="font-size:3vmin;"><code>TO GATHER</code></pre>
                    <pre><code>해결이 안 되는 문제가 있다면 스스로 모임을 구성해보세요. 분명히 나와 같은 고민을 갖고 있는 사람이 있을거에요.</code></pre>
                    <br>
                    <pre style="font-size:3vmin;"><code>BE TOGETHER</code></pre>
                    <pre><code>이미 나와 같은 고민을 하고 있었던 사람이 있지 않았을까요? 모임을 찾고 함께 문제에 대해 고민해봐요.</code></pre>
                </div>
                <br>
                <br>
            </div>
        </section>
        <section class="section section--code">
            <div class="container">
                <h2 class="section-title" data-aos="fade-right" data-aos-delay="400">START TOGETHER</h2>
                <img src="/static/img/communication.png" width="150" height="150" align="left" data-aos="fade-in" data-aos-dely="800">
                <div class="secton-header" data-aos="fade-left" data-aos-delay="1200" style="color:white; text-align:right;">
                    <br>
                    <pre><code>이제 우리는 멋진 채팅 플랫폼을 타고 여행을 할 준비가 되었습니다.</code></pre>
                    <pre><code>TOGETHER와 함께 광활한 네트워크 공간을 누리고 공유의 힘을 체험해보세요</code></pre>
                    <pre><code>당신은 분명히 더욱 빛나는 사람이 되어있을 겁니다!</code></pre>
                    <pre style="font-size:3vmin;"><code> START TOGETHER! STAY TOGETHER!</code></pre>
                </div>
                <br>
                <br>
            </div>
        </section>
        <section class="container_btn">
            <div class="buttons">
                <a href="{% url 'to_gather' %}" class="btn-1">TO GATHER</a>
                <a href="{% url 'chat:be_together' %}" class="btn-1">BE TOGETHER</a>
              </section>


 		<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
 		<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script>
            AOS.init({

            });
        </script>
        <script>
            hljs.initHighlightingOnLoad();
            $('.hero__scroll').on('click', function(e) {
                $('html, body').animate({
                    scrollTop: $(window).height()
                }, 1200);
            });
        </script>
    </body>
</html>

website/templates/website/to_gather.html
{%extends 'website/base.html'%}

{%block menu_to_gather%}
<strong><u>To gather</u></strong>
{%endblock%}


{%block menu_be_together%}
Be together
{%endblock%}

{%block contents%}
<div id = "div_contents_category">
  {%for post in posts %}
    <li><a href="{% url 'to_gather_list' pk=post.pk %}">{{post.title}}</a></li>
  {%endfor%}

  <div class = "list_header" >
      <a href="{% url 'to_gather_new' %}"><span class="glyphicon glyphicon-plus"></span></a>
    </div>
</div>



{%endblock%}

website/templates/website/to_gather_edit.html
{% extends 'website/base.html' %}

{%block contents%}
  <h2>New Post for to_gather</h2>

  <form method = "POST" class = "post-form"> {% csrf_token %}
    {{ form }}
    <button type = "submit" class = "save btn btn-default">Save</button>
  </form>
{%endblock%}

website/templates/website/to_gather_list.html
{%extends 'website/base.html'%}

{%block menu_to_gather%}
<strong><u>To gather</u></strong>
{%endblock%}

{%block menu_be_together%}
Be together
{%endblock%}

{%block contents%}
<div class = "post">
  <h1><strong>이곳은 '{{ post.title }}' 스터디를 위한 방입니다.</strong></h1>
  <p>{{ post.text|linebreaksbr }}</p>

</div>



 <a class="btn btn-default" href="{% url 'to_gather_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
{%endblock%}